sudo: required

services:
  - docker

jobs:
  include:
    - stage: build
      script:
      - make build


deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: 23_create_docker_release