sudo: required

services:
  - docker

jobs:
  include:
    - stage: build
      script:
      - make build

after_success:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else exit 0 ; fi`
#  - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
  - export REPO=tyro/rabbit-amazon-bridge
  - docker build -f Dockerfile.deploy -t $REPO:0.1 .
#  - docker tag $REPO:$COMMIT $REPO:$TAG
#  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
#  - docker push $REPO