sudo: required

services:
  - docker

jobs:
  include:
    - stage: build
      script:
      - make build

after_success:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else exit 0 ; fi`
  - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
  - export REPO=tyro/rabbit-amazon-bridge
  - docker build -f Dockerfile.deploy -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO