sudo: required

services:
  - docker

jobs:
  include:
    - stage: build
      script:
      - make build
    - stage: deploy
      script:
      - export TAG=test-branch
      - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
      - export REPO=tyro/rabbit-amazon-bridge
      - docker build -f Dockerfile.deploy -t $REPO:$TRAVIS_COMMIT.
      - docker tag $REPO:$TRAVIS_COMMIT $REPO:$TAG
      - docker tag $REPO:$TRAVIS_COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
      - docker push $REPO