version: '3'
services:
  sut:
    image: ${DOCKER_BUILD_IMAGE}
    command: wait-for-it/wait-for-it.sh rabbitmq:15672 -t 60 -- wait-for-it/wait-for-it.sh localsqs:9324 -t 60 -- /usr/bin/mvn --batch-mode verify -P docker-integration-tests
    depends_on:
      - rabbitmq
      - localsqs
  rabbitmq:
      image: rabbitmq:3.7.7-management
      ports:
        - "15671:15671"
        - "5672:5672"
      environment:
        RABBITMQ_DEFAULT_VHOST: /
  localsqs:
    image: softwaremill/elasticmq:latest
    ports:
      - 9324:9324
    volumes:
      - "./local-sqs/elasticmq-docker-integration-test.conf:/opt/elasticmq.conf"
