version: '3.2'
services:
  rabbitmq:
    image: rabbitmq:3.7.7-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_VHOST: /
  localsqs:
    image: softwaremill/elasticmq
    ports:
      - 9324:9324
    volumes:
      - "./local-sqs/elasticmq.conf:/opt/elasticmq.conf"
